### POST
POST http://localhost:3000/login
Content-Type: application/json

{
    "username":"Thinh",
    "password":"440"
}

### GET

GET http://localhost:3000/status


### protected

GET http://localhost:3000/protected
